### ISSUE TITLE
Reporte de Interfaz visual 

### ISSUE THREAD

**Issue by Aricel117** [SistemasTecTlaxiaco/practica-de-visual-studio-Aricel117#2]
[Reporte Practica 2.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-visual-studio-Aricel117/files/6755888/Reporte.Practica.2.pdf)

**Comment by javiern-778** [comment]
EXELENTE trabajo 20

**Comment by josealfredo79** [comment]
Hay que utilizar adecuadamente la herramienta de GtiHub para comunicarse
